spring:
  application:
    name: springcontainers
  profiles:
    active: local
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
